.TH sslsniff 1
.SH NAME
sslsniff \- simple tool to monitor SSL connections.
.SH SYNOPSIS
.B ./sslsniff
[\fB\-i\fR \fIINTERFACE\fR]
[\fB\-r\fR \fIFILE\fR]
.TP
(sometimes sudo for interface is needed.)
.SH DESCRIPTION
.B sslsniff
Captures SSL connections either from the pcap/pcapng file or from the interface.
.SH OPTIONS
.TP
.BR \-i 
Listen from the given \fIINTERFACE\fR name/number
.TP
.BR \-r 
Captures the connection from the given \fIFILE\fR in pcap/pcapng format
.TP
.BR \-h ", " \-\-help
Shows help
.TP
.BR "no option"
Shows help and list available interfaces
.SH OUTPUT
.TP
.B <TIMESTAMP>,<SOURCE_IP>,<SOURCE_PORT>,<DESTINATION_IP>,<SNI>,<SSL DATA [bytes]>,<PACKETS COUNT>,<DURATION [s]>
.SH EXAMPLES
.TP
.BR "./sslsniff -r example.pcapng"
2020-10-13 15:31:33.663920,10.10.10.20,49936,192.200.200.200,www.example.com,69420,42,0.161493
.TP
.B sudo ./sslsniff -i 2
2020-10-22 03:25:06.581448,147.229.192.151,38836,147.229.9.21,wis.fit.vutbr.cz,47231,51,39.732284


